// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bszbcoekntzqptrlwofg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzemJjb2VrbnR6cXB0cmx3b2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTkxNDcsImV4cCI6MjA2NDYzNTE0N30.grSjnH8cZ3xjsZlvnl5nRL-UsGaNCrfIkgBjOBzUKZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);